[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
glam = "0.29.0"
itertools = "0.13.0"
nom = "7.1.3"
rayon = "1.10.0"
divan = "0.1.7"
miette = { version = "7.4", features = ["fancy"] }
