[package]
name = "day-02"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools.workspace = true
nom.workspace = true
miette.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "day-02-bench"
path = "benches/benchmarks.rs"
harness = false
